export const homeprod3 = [
  {
    id: 1,
    image: 'product-1.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 2,
    image: 'product-2.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 3,
    image: 'product-6.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 1,
    image: 'product-1.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 2,
    image: 'product-2.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 3,
    image: 'product-6.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 1,
    image: 'product-1.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 2,
    image: 'product-2.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 3,
    image: 'product-6.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
];

export const decor = [
  {
    id: 1,
    image: 'product-7.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 2,
    image: 'product-8.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 3,
    image: 'product-19.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 179,
    previous_price: 288,
    best_seller: true,
  },
];
export const products = [
  {
    id: 1,
    image: 'product-1.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 2,
    image: 'product-2.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: true,
  },
  {
    id: 3,
    image: 'product-3.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 4,
    image: 'product-4.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 5,
    image: 'product-5.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 6,
    image: 'product-6.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 7,
    image: 'product-7.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
  {
    id: 8,
    image: 'product-8.jpg',
    name: 'Product Name',
    mg: 100,
    brand: 'Omoron',
    price: 149,
    previous_price: 288,
    best_seller: false,
  },
];
